# docker-compose.yml
version: '3'
services:
  composer:
    image: composer:2.0
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  php:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
